name: CI Build & Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x, 22.x]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9.12.3
        
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
        
    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
          
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Test Style Dictionary configuration
      run: |
        cd packages/design-tokens
        node test-build.js || echo "Style Dictionary test failed, continuing..."
        
    - name: Run build
      run: pnpm build
      
    - name: Run typecheck
      run: pnpm typecheck
      
    - name: Run tests
      run: pnpm test
      
    - name: Test clean script
      run: pnpm clean
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: build-output-node-${{ matrix.node-version }}
        path: |
          packages/*/dist/
          packages/core/storybook-static/
        retention-days: 1